layout: dataset
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
reveal: False
postdir: ../../../lawrennd/ods/_datasets/
notebookdir: ../../../lawrennd/ods/notebooks/pods/datasets/
slidedir: ../../../lawrennd/ods/assets/diagrams/
diagramdir: ../assets/diagrams/
writediagramdir: .
transition: None
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _datasets
