author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
room: LT2
venue: William Gates Building
talkcss: https://inverseprobability.com/assets/css/talks.css
postsdir: ../../../mlatcl/advds/_lectures/
slidesdir: ../../../mlatcl/advds/slides/
notesdir: ../../../mlatcl/advds/_notes/
notebooksdir: ../../../mlatcl/advds/_notebooks/
writediagramsdir: .
scriptsdir: ./scripts/
diagramsdir: ./slides/diagrams/
baseurl: "advds/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.io/" # the base hostname & protocol for your site
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _advds
transition: None
  
