layout: lecture
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
postdir: ../../../mlatcl/mlai/_lectures/
slidedir: ../../../mlatcl/mlai/slides/
notedir: ../../../mlatcl/mlai/_notes/
notebookdir: ../../../mlatcl/mlai/_notebooks/
writediagramsdir: .
diagramsdir: ./slides/diagrams/
baseurl: "mlai/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.com/" # the base hostname & protocol for your site
time:
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _mlai
transition: None
