author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
pptx: True
potx: ../_includes/judge-exec-reference.potx
postdir: ../../../mlatcl/execed/_lectures/
slidedir: ../../../mlatcl/execed/slides/
notedir: ../../../mlatcl/execed/_notes/
notebookdir: ../../../mlatcl/execed/_notebooks/
writediagramdir: .
diagramdir: ./slides/diagrams/
baseurl: "execed/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.com/" # the base hostname & protocol for your site
transition: None
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _execed
