layout: notebook
author:
- family: Lawrence
  given: Neil D.
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
ipynb: True
reveal: False
postdir: ../../../lawrennd/gpy-gallery/_gallery/
notebookdir: ../../../lawrennd/gpy-gallery/_notebooks/
transition: None
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _gpy
