author:
- given: Neil D.
  family: Lawrence
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
talkscam:
url: https://inverseprobability.com/
talkcss: https://inverseprobability.com/assets/css/talks.css
baseurl: talks/
postsdir: ../_posts/
notebooksdir: ../_notebooks/
slidesdir: ../slides/
diagramsdir: ./slides/diagrams/
writediagramsdir: .
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _ml
