author:
- given: Neil D.
  family: Lawrence
  gscholar: r3SJcvoAAAAJ
  institute: University of Cambridge
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
talkscam:
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _ml