author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
room: LT1
venue: William Gates Building
talkcss: https://inverseprobability.com/assets/css/talks.css
postsdir: ../../../mlatcl/deepnn/_lectures/
slidesdir: ../../../mlatcl/deepnn/slides/
notesdir: ../../../mlatcl/deepnn/_notes/
notebooksdir: ../../../mlatcl/deepnn/_notebooks/
writediagramsdir: .
scriptsdir: ../scripts/
diagramsdir: ./slides/diagrams/
baseurl: "deepnn/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.io/" # the base hostname & protocol for your site
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _deepnn
transition: None
